#ifndef ZEBRAL_ESP32CAM_ZBA_ERR_H_
#define ZEBRAL_ESP32CAM_ZBA_ERR_H_

#ifdef __cplusplus
extern "C"
{
#endif

  /// Return codes
  typedef enum zba_err
  {
    ZBA_OK    = 0x0000,
    ZBA_ERROR = 0x8000,
    ZBA_MODULE_NOT_INITIALIZED,
    ZBA_CAM_ERROR = 0x8100,
    ZBA_CAM_INIT_FAILED,
    ZBA_CAM_DEINIT_FAILED,
    ZBA_WIFI_ERROR = 0x8200,
    ZBA_WIFI_INIT_FAILED,
    ZBA_WIFI_NOT_CONFIGURED,
    ZBA_SD_ERROR = 0x8300,
    ZBA_SD_NOT_PRESENT,
    ZBA_SD_INVALID_PATH,
    ZBA_SD_PATH_NOT_DIR,
    ZBA_SD_END_SEARCH,
    ZBA_CONFIG_ERROR = 0x8400,
    ZBA_CONFIG_INIT_ERROR,
    ZBA_CONFIG_WRITE_OPEN_FAILED,
    ZBA_CONFIG_WRITE_FAILED,
    ZBA_CONFIG_READ_FAILED,
    ZBA_CONFIG_NEW,
    ZBA_CONFIG_NOT_INITIALIZED,
    ZBA_CONFIG_ERASE_FAILED,
    ZBA_CONFIG_ERASE_COMMIT_FAILED,
    ZBA_CONFIG_NOT_AUTHED,
    ZBA_LED_ERROR = 0x8500,
    ZBA_LED_ERR_SD_ACTIVE,
    ZBA_WEB_ERROR = 0x8600,
    ZBA_WEB_INIT_FAILED,
    ZBA_WEB_DEINIT_FAILED,
    ZBA_STREAM_ERROR = 0x8700,
    ZBA_STREAM_INIT_FAILED,
    ZBA_PINS_ERROR = 0x8800,
    ZBA_PINS_GPIO_CONFIG_ERROR,
    ZBA_PINS_DIGITAL_WRITE_ERROR,
    ZBA_PINS_RESET_ERROR,
    ZBA_UTIL_ERROR = 0x8900,
    ZBA_UTIL_UART_ERROR,
    //-----------------------
    ZBA_HIGHEST
  } zba_err_t;

#ifdef __cplusplus
}
#endif

#endif  // ZEBRAL_ESP32CAM_ZBA_ERR_H_
